version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  check-updated-files:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          config-path: .circleci/continue_config.yml
          mapping: |
            terraform/vpc/.* run-vpc-changes true
            terraform/ec2/.* run-ec2-changes true